services:
  # Backend API Service
  - type: web
    name: radix-tribes-backend
    env: node
    plan: free
    buildCommand: |
      cd shared && npm install && npm run build &&
      cd ../backend && npm install && npm run build &&
      npx prisma generate
    startCommand: |
      cd backend &&
      npx prisma migrate deploy &&
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: radix-tribes-postgres
          property: connectionString
      - key: FRONTEND_URL
        value: https://radix-tribes-frontend.onrender.com
    healthCheckPath: /health

  # Frontend Static Site
  - type: static_site
    name: radix-tribes-frontend
    buildCommand: |
      cd shared && npm install && npm run build &&
      cd ../frontend && npm install && npm run build
    publishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://radix-tribes-backend.onrender.com

databases:
  - name: radix-tribes-postgres
    databaseName: radix_tribes
    user: postgres
    plan: free
