services:
  # Backend API Service
  - type: web
    name: radix-tribes-backend
    env: node
    plan: free
    buildCommand: |
      cd shared && npm install && npm run build &&
      cd ../backend && npm install && npm run build
    startCommand: |
      cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_URL
        fromDatabase:
          name: radix-tribes-redis
          property: connectionString
      - key: FRONTEND_URL
        value: https://radix-tribes-frontend.onrender.com
    healthCheckPath: /health

  # Frontend Web Service (serving static files)
  - type: web
    name: radix-tribes-frontend
    env: static
    buildCommand: |
      cd shared && npm install && npm run build &&
      cd ../frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://radix-tribes-backend.onrender.com

databases:
  - name: radix-tribes-redis
    databaseName: radix_tribes_redis
    user: redis
    plan: free
