services:
  # Backend API Service
  - type: web
    name: radix-tribes-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      echo "=== Installing shared dependencies ===" &&
      npm install --prefix shared --include=dev &&
      echo "=== Building shared package ===" &&
      npm run build --prefix shared &&
      echo "=== Installing backend dependencies ===" &&
      npm install --prefix backend --include=dev &&
      echo "=== Building backend package ===" &&
      npm run build --prefix backend &&
      echo "=== Generating Prisma client ===" &&
      cd backend && npx prisma generate &&
      echo "=== Build complete ==="
    startCommand: |
      cd backend &&
      npx prisma migrate deploy &&
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: radix-tribes-postgres
          property: connectionString
      - key: FRONTEND_URL
        value: https://radix-tribes-frontend.onrender.com
      - key: ADMIN_PASSWORD
        value: Gravedaleh1!
    healthCheckPath: /health

  # Frontend Web Service (serving static files)
  - type: web
    name: radix-tribes-frontend
    env: static
    rootDir: .
    buildCommand: |
      npm install --prefix shared --include=dev &&
      npm run build --prefix shared &&
      npm install --prefix frontend --include=dev &&
      npm run build --prefix frontend
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://radix-tribes-backend.onrender.com

databases:
  - name: radix-tribes-postgres
    databaseName: radix_tribes
    user: radix_tribes_user
    plan: free
