version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: radix_tribes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/radix_tribes
      - PORT=3000
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/backend/src
      - ./shared/src:/app/shared/src
      - ./backend/prisma:/app/backend/prisma
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./shared/src:/app/shared/src
    command: npm run dev

volumes:
  postgres_data:
